# Production Environment Overrides
environment: prod

web:
  replicas: 1
  resources:
    requests:
      memory: 64Mi
      cpu: 25m
    limits:
      memory: 256Mi
      cpu: 200m

ingress:
  enabled: true
  tlsEnabled: true
  certManagerIssuer: letsencrypt-prod-dns01
  domain: nuvoxel.com
